from Basic_Gates import Logic_Gate_module as lgm
class Half_Adder:
    '''
    Docstring for Half_Adder
    This class is used for constructing a half adder. Users are expected to instantiate this class, preferably with the name 'half_adder'
    Here
    in1=Input value of the first bit
    in2=Input value of the second bit
    sum= The sum of in1 and in2 (in1^in2)
    cout=The carry produced by the addition of in1 and in2(in1 & in2)
    The expressioms for sum and cout can be derived from the truth table of the half adder.
    '''
    def __init__(self,in1,in2):
        xor_gate=lgm.Xor_Class(in1,in2)
        self.sum=xor_gate.output()
        and_gate=lgm.And_Class(in1,in2)
        self.cout=and_gate.output()
    def output(self):
        return self.sum,self.cout

class Full_Adder:
    '''
    Docstring for Full_Adder
    This class is used for constructing a full adder. Users are expected to instantiate this class, preferably with the name 'full_adder'
    We create the Full adder using two half adders.
    Here,
    in1=The first input bit
    in2=The second input bit
    cin=The Carry in from the previous stage
    half_adder1=First instance of the Half_Adder class.Produces interim_sum (in1^in2) and produces interim_cout1(in1 & in2)
    half_adder2=Second instance of the Half_Adder class. Produces sum(in1^in2^cin) and produces interim_cout2(cin&(in1^in2))
    sum=The final sum produced
    cout=The final carry out produced.(Produced using or_gate(interim_cout1, interim_cout2))
    The expressions for sum and cout can be derived using the truth table for the full adder.
    '''
    def __init__(self,in1,in2,cin):
        half_adder1=Half_Adder(in1,in2)
        interim_sum,interim_cout1=half_adder1.output()
        half_adder2=Half_Adder(interim_sum,cin)
        self.sum,interim_cout2=half_adder2.output()
        or_gate=lgm.Or_Class(interim_cout1,interim_cout2)
        self.cout=or_gate.output()
    def output(self):
        return self.sum,self.cout

class RippleCarry_Adder:
    '''
    Docstring for RippleCarry_Adder
    This class is used for constructing a Ripple carry adder. Users are expected to instantiate this class, preferably with the name 'rca'
    The RCA would be generated by combining 64 full adders in series.
    Here,
    in1_vec=The first input vector(input bus of width 64)
    in2_vec=The second input vector(input bus of width 64)
    cin=The carry in for the first adder
    adder_list=An efficient way to chain 64 full adders
    output_vec=The output vector where each wire carries the bitwise sum of each full adder
    cout_final=The final carry out of the adder to be stored in carry flag
     
    '''
    def __init__(self,in1_vec,in2_vec,cin):
        full_adder0=Full_Adder(in1_vec[0],in2_vec[0],cin)
        self.adder_list=[0]*64
        self.adder_list[0]=full_adder0
        for i in range (1,64):
            self.adder_list[i]=Full_Adder(in1_vec[i],in2_vec[i],self.adder_list[i-1].cout)
    def output(self,output_vec):
        for i in range (0,64):
            output_vec[i]=self.adder_list[i].sum
        cout_final=self.adder_list[63].cout 
        return output_vec,cout_final
           
            
            
    